name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [py38, py39, py311, py312]

    steps:
    - uses: actions/checkout@v4

    - uses: prefix-dev/setup-pixi@v0.5.1
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      with:
        cache: false
        environments: >-
          ${{ matrix.python-version }}

    - name: Run build
      run: pixi run -e ${{ matrix.python-version }} build

    - name: Run test
      run: pixi run -e ${{ matrix.python-version }} test
